// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdwydorgfyggrbxpjuzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "380e906c148ec520ef7b8fcf2002a77d5747a62c0103a3cc1cd6eda090ce4e74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
